# Environment-specific values for my-website-2 (dev)
replicaCount: 1

image:
  tag: "latest"

ingress:
  enabled: false
  hosts:
    - host: my-website-2.dev.example.com
      paths:
        - path: /
          pathType: Prefix
